# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray

- type: subscribe
  options:
    url: http://proxypool.turinglabs.net/upload/daily/v2ray
    
- type: subscribe
  options:
    url: http://proxypool.turinglabs.net/upload/daily/shadowsocksR
    
- type: subscribe
  options:
    url: http://proxypool.turinglabs.net/upload/daily/shadowsocks
    
- type: subscribe
  options:
    url: https://getlsjlink.com/link/df7b1986ba083f4355955dc5dbd4d4ced69570e7
    
- type: subscribe
  options:
    url: https://dingyue.suying666.info/link/iWk8PoBxfym705SX?sub=1
 
- type: subscribe
  options:
    url: https://smallairport.icu/api/v1/client/subscribe?token=12155e1270aea61fc7ac36ceffb59fb5
        
- type: subscribe
  options:
    url: https://tudog-rss.com/link/ERVdxxFOl7e7cshu?sub=3
  
- type: subscribe
  options:
    url: https://rss.cnrss.xyz/link/Zq1P3T2S91eAgqKm?mu=2

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html
    
# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html
    
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-2-1.html
    
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-36-1.html
    
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-50-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml

- type: clash
  options:
    url: https://proxypool.ga/clash/proxies
    
- type: clash
  options:
    url: https://proxypoolss.tk/clash/proxies

# 某个网站抓取
- type: web-freessrxyz
  options:
